detectnet_node:
    prototxt_path: "/home/nvidia/jetson-inference/build/aarch64/bin/networks/DetectNet-COCO-Dog/deploy.prototxt"
    model_path: "/home/nvidia/jetson-inference/build/aarch64/bin/networks/DetectNet-COCO-Dog/snapshot_iter_38600.caffemodel"
    mean_binary_path: "/home/nvidia/jetson-inference/build/aarch64/bin/networks/DetectNet-COCO-Dog/mean.binaryproto"

