detectnet_node:
    prototxt_path: "/home/nvidia/jetson-inference/build/aarch64/bin/networks/multiped-500/deploy.prototxt"
    model_path: "/home/nvidia/jetson-inference/build/aarch64/bin/networks/multiped-500/snapshot_iter_178000.caffemodel"
    mean_binary_path: "/home/nvidia/jetson-inference/build/aarch64/bin/networks/multiped-500/mean.binaryproto"

