detectnet_node:
    prototxt_path: "/home/nvidia/jetson-inference/build/aarch64/bin/networks/ped-100/deploy.prototxt"
    model_path: "/home/nvidia/jetson-inference/build/aarch64/bin/networks/ped-100/snapshot_iter_70800.caffemodel"
    mean_binary_path: "/home/nvidia/jetson-inference/build/aarch64/bin/networks/ped-100/mean.binaryproto"

